apiVersion: v1 
kind: Service
metadata: 
  name: redis
  labels:
    name: redis-service
    app: demo-guestbook

spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-app-pod
    app: demo-guestbook
